name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run lint
        run: bun lint
      
      - name: Run typecheck
        run: bun typecheck

  build-extension:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build extension
        run: bun run --filter @youtube-ai-moderator/extension build
      
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: apps/extension/dist

  build-site:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build site
        run: bun run --filter @youtube-ai-moderator/site build
      
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: apps/site/.next